// === Australia (AU) Drugs ===
panadol_au: { id: "panadol_au", nameKR: "파나돌", nameVN: "Panadol", nameUS: "Panadol", nameAU: "Panadol", ingredient: "Paracetamol 500mg", dosageKR: "1~2정, 4~6시간 간격, 하루 최대 8정", dosageVN: "1~2 viên, cách 4~6 giờ, tối đa 8 viên/ngày", dosageUS: "1-2 tabs, every 4-6hrs, max 8/day", dosageAU: "1-2 tablets, every 4-6 hours, max 8 tablets/day (4g). S2 Pharmacy Medicine", precautionKR: "음주 시 간독성. 다른 파라세타몰 약 중복 금지. 🦟 QLD 북부 뎅기열 의심 시 파라세타몰만 사용", precautionVN: "Nguy cơ gan khi uống rượu. Không dùng chung paracetamol khác", precautionUS: "Liver risk with alcohol. No other paracetamol products", precautionAU: "Liver risk with alcohol. No other paracetamol products. S2—available on pharmacy shelf. 🦟 Dengue (nth QLD): paracetamol only, no NSAIDs" },

nurofen_au: { id: "nurofen_au", nameKR: "뉴로펜", nameVN: "Nurofen", nameUS: "Nurofen", nameAU: "Nurofen", ingredient: "Ibuprofen 200mg", dosageKR: "1~2정, 식후, 4~6시간 간격", dosageVN: "1~2 viên, sau ăn, cách 4~6 giờ", dosageUS: "1-2 tabs, with food, every 4-6hrs", dosageAU: "1-2 tablets, with food, every 4-6 hours. S2 Pharmacy Medicine", precautionKR: "공복 금지. 임신 20주 이후 금기. 🦟 뎅기열 의심 시 금지", precautionVN: "Không uống lúc đói. Cấm sau 20 tuần thai. 🦟 Sốt xuất huyết cấm", precautionUS: "Not on empty stomach. No after 20wks pregnancy. 🦟 No with dengue", precautionAU: "Take with food. Not after 20 weeks pregnancy. 🦟 Contraindicated with suspected dengue" },

panadol_extra_au: { id: "panadol_extra_au", nameKR: "파나돌 엑스트라", nameVN: "Panadol Extra", nameUS: "Panadol Extra", nameAU: "Panadol Extra", ingredient: "Paracetamol 500mg + Caffeine 65mg", dosageKR: "1~2정, 4~6시간 간격", dosageVN: "1~2 viên, cách 4~6 giờ", dosageUS: "1-2 tabs, every 4-6hrs", dosageAU: "1-2 tablets, every 4-6 hours. S2", precautionKR: "카페인 민감자 주의. 다른 파라세타몰 약 중복 금지", precautionVN: "Người nhạy cảm caffein cẩn thận. Không dùng chung paracetamol khác", precautionUS: "Caffeine sensitive caution. No other paracetamol", precautionAU: "Caffeine sensitive caution. No other paracetamol products" },

codral_au: { id: "codral_au", nameKR: "코드랄 데이/나이트", nameVN: "Codral Day/Night", nameUS: "Codral Day/Night", nameAU: "Codral Cold & Flu Day/Night", nameLocal: "Codral", pronKR: "코드랄", pronEN: "cod-ral", ingredient: "Day: Paracetamol 500mg+Phenylephrine 5mg+DXM 10mg / Night: Paracetamol 500mg+Chlorphenamine 2mg+DXM 10mg", dosageKR: "Day 2캡슐 4~6시간 / Night 2캡슐 취침 전", dosageVN: "Ngày 2 viên cách 4~6 giờ / Đêm 2 viên trước ngủ", dosageUS: "Day 2 caps every 4-6hrs / Night 2 caps at bedtime", dosageAU: "Day: 2 capsules every 4-6hrs (max 6/day). Night: 2 capsules at bedtime (max 2/day). S2. Not for under 12", precautionKR: "12세 미만 금지. 다른 파라세타몰 약 병용 금지. Night→졸음→운전 금지", precautionVN: "Cấm dưới 12 tuổi. Không dùng chung paracetamol khác. Đêm→buồn ngủ", precautionUS: "No under 12. No other paracetamol. Night→drowsy→no driving", precautionAU: "Not for under 12. No other paracetamol products. Night capsules cause drowsiness—do not drive. S2" },

codral_original_au: { id: "codral_original_au", nameKR: "코드랄 오리지널", nameVN: "Codral Original", nameUS: "Codral Original", nameAU: "Codral Original Day/Night", ingredient: "Day: Paracetamol 500mg+Pseudoephedrine 30mg / Night: +Triprolidine 1.25mg", dosageKR: "Day 2정(오전/오후) / Night 2정 취침 전", dosageVN: "Ngày 2 viên / Đêm 2 viên trước ngủ", dosageUS: "Day 2 tabs / Night 2 tabs at bedtime", dosageAU: "Day: 2 tablets (morning & afternoon). Night: 2 tablets at bedtime. S3—pharmacist consultation required", precautionKR: "S3 약사 상담 필수. 고혈압·심장·갑상선·당뇨·녹내장·전립선비대 금기", precautionVN: "S3 phải hỏi dược sĩ. Cao huyết áp/tim/giáp/tiểu đường cấm", precautionUS: "S3 pharmacist only. Hypertension/heart/thyroid/diabetes contraindicated", precautionAU: "S3 Pharmacist Only—must consult pharmacist. Contraindicated: hypertension, heart disease, thyroid, diabetes, glaucoma, prostate. ID verification required" },

durotuss_au: { id: "durotuss_au", nameKR: "듀로터스", nameVN: "Duro-Tuss", nameUS: "Duro-Tuss", nameAU: "Duro-Tuss", nameLocal: "Duro-Tuss", pronKR: "듀로터스", pronEN: "dew-ro-tus", ingredient: "Dextromethorphan (dry cough) or Guaifenesin+Bromhexine (chesty)", dosageKR: "10ml, 하루 3~4회", dosageVN: "10ml, 3~4 lần/ngày", dosageUS: "10ml, 3-4 times/day", dosageAU: "10ml, 3-4 times daily. S2 (basic) / S3 (night/forte). Not for under 2", precautionKR: "야간용 Doxylamine→졸음→운전 금지. MAO 억제제 금기. 2세 미만 금지", precautionVN: "Bản đêm gây buồn ngủ. MAOI cấm. Dưới 2 tuổi cấm", precautionUS: "Night version: drowsy. No MAOIs. No under 2", precautionAU: "Night version (Doxylamine): drowsiness—do not drive. MAOIs contraindicated. Not for under 2" },

bisolvon_au: { id: "bisolvon_au", nameKR: "비솔본", nameVN: "Bisolvon", nameUS: "Bisolvon", nameAU: "Bisolvon Chesty Forte", nameLocal: "Bisolvon", pronKR: "비솔본", pronEN: "bi-sol-von", ingredient: "Bromhexine HCl 8mg", dosageKR: "1정, 하루 3회", dosageVN: "1 viên, 3 lần/ngày", dosageUS: "1 tab, 3 times/day", dosageAU: "1 tablet, 3 times daily. S2. Drink plenty of water", precautionKR: "충분한 수분 섭취. 소화성 궤양 주의", precautionVN: "Uống nhiều nước. Loét dạ dày cẩn thận", precautionUS: "Drink plenty of water. Peptic ulcer caution", precautionAU: "Drink plenty of fluids to help loosen mucus. Peptic ulcer caution" },

telfast_au: { id: "telfast_au", nameKR: "텔패스트", nameVN: "Telfast", nameUS: "Telfast", nameAU: "Telfast", nameLocal: "Telfast", pronKR: "텔패스트", pronEN: "tel-fast", ingredient: "Fexofenadine HCl 180mg", dosageKR: "1정, 하루 1회", dosageVN: "1 viên, 1 lần/ngày", dosageUS: "1 tab, once daily", dosageAU: "1 tablet (180mg), once daily. S2. Non-drowsy", precautionKR: "졸음 없음. 제산제와 동시 복용 금지(흡수 40% 감소). 자몽주스 주의", precautionVN: "Không buồn ngủ. Không dùng chung antacid. Cẩn thận nước bưởi", precautionUS: "Non-drowsy. No antacids simultaneously (40% reduced absorption). Grapefruit juice caution", precautionAU: "Non-drowsy. Do not take with aluminium/magnesium antacids (40% reduced absorption). Avoid grapefruit juice" },

zyrtec_au: { id: "zyrtec_au", nameKR: "지르텍", nameVN: "Zyrtec", nameUS: "Zyrtec", nameAU: "Zyrtec", ingredient: "Cetirizine HCl 10mg", dosageKR: "1정, 하루 1회(취침 전)", dosageVN: "1 viên, 1 lần/ngày (trước ngủ)", dosageUS: "1 tab, once daily (bedtime)", dosageAU: "1 tablet, once daily (preferably at bedtime). S2", precautionKR: "졸음 가능. 신장질환 시 용량 조절", precautionVN: "Có thể buồn ngủ. Bệnh thận điều chỉnh liều", precautionUS: "May cause drowsiness. Kidney disease: dose adjustment", precautionAU: "May cause drowsiness. Kidney disease: dose adjustment. Alcohol may enhance drowsiness" },

claratyne_au: { id: "claratyne_au", nameKR: "클래러타인", nameVN: "Claratyne", nameUS: "Claratyne", nameAU: "Claratyne", nameLocal: "Claratyne", pronKR: "클래러타인", pronEN: "cla-ra-tine", ingredient: "Loratadine 10mg", dosageKR: "1정, 하루 1회", dosageVN: "1 viên, 1 lần/ngày", dosageUS: "1 tab, once daily", dosageAU: "1 tablet, once daily. S2. Non-drowsy", precautionKR: "졸음 매우 적음. 간질환 시 격일 복용", precautionVN: "Ít gây buồn ngủ. Bệnh gan uống cách ngày", precautionUS: "Very low drowsiness. Liver disease: every other day", precautionAU: "Very low drowsiness. Severe liver disease: every other day dosing" },

gaviscon_au: { id: "gaviscon_au", nameKR: "개비스콘", nameVN: "Gaviscon", nameUS: "Gaviscon", nameAU: "Gaviscon Extra Strength", ingredient: "Sodium Alginate 1000mg + Potassium Bicarbonate 200mg + Calcium Carbonate 200mg", dosageKR: "10~20ml, 식후 및 취침 전", dosageVN: "10~20ml, sau ăn và trước ngủ", dosageUS: "10-20ml, after meals & bedtime", dosageAU: "10-20ml, after meals and at bedtime. S2. Note: AU formula differs from UK (no Al hydroxide)", precautionKR: "저칼륨 식이 주의(K Bicarbonate). 신장질환 의사 상담. 다른 약과 2시간 간격", precautionVN: "Chế độ ít kali cẩn thận. Bệnh thận hỏi bác sĩ", precautionUS: "Low potassium diet caution. Kidney disease: consult doctor. Space other meds 2hrs", precautionAU: "Low potassium diet caution. Kidney disease: consult pharmacist. Space 2hrs from other medicines. AU formula: no aluminium hydroxide" },

nexium_au: { id: "nexium_au", nameKR: "넥시움 24HR", nameVN: "Nexium 24HR", nameUS: "Nexium 24HR", nameAU: "Nexium 24HR", nameLocal: "Nexium 24HR", pronKR: "넥시움", pronEN: "nex-ee-um", ingredient: "Esomeprazole 20mg", dosageKR: "1정, 하루 1회, 최소 7일~최대 14일", dosageVN: "1 viên, 1 lần/ngày, 7~14 ngày", dosageUS: "1 tab, once daily, 7-14 days", dosageAU: "1 tablet daily, minimum 7 days up to 14 days. S2 Pharmacy Medicine (not S3)", precautionKR: "14일 초과 자가 복용 금지. 18세 미만 금지. 클로피도그렐 병용 주의. 수유부 금기", precautionVN: "Không quá 14 ngày. Cấm dưới 18 tuổi. Cho con bú cấm", precautionUS: "No more than 14 days. No under 18. Clopidogrel interaction. Breastfeeding contraindicated", precautionAU: "Max 14 days self-treatment. Not for under 18. Clopidogrel interaction. Breastfeeding contraindicated. S2—pharmacy shelf purchase" },

imodium_au: { id: "imodium_au", nameKR: "이모디움", nameVN: "Imodium", nameUS: "Imodium", nameAU: "Imodium", ingredient: "Loperamide HCl 2mg", dosageKR: "초회 2정, 이후 설사마다 1정, 하루 최대 8정", dosageVN: "Đầu tiên 2 viên, sau mỗi lần 1 viên, tối đa 8/ngày", dosageUS: "First 2 tabs, then 1 per stool, max 8/day", dosageAU: "Initially 2 capsules, then 1 after each loose stool, max 8/day (16mg). S2", precautionKR: "12세 미만 금지. 혈변·발열 시 금지. 48시간 이내 개선 없으면 의사", precautionVN: "Cấm dưới 12 tuổi. Máu/sốt cấm. 48 giờ không cải thiện→bác sĩ", precautionUS: "No under 12. No with bloody stool/fever. 48hrs→doctor", precautionAU: "Not for under 12. Do not use with bloody diarrhoea or fever. 48hrs no improvement→see GP" },

hydralyte_au: { id: "hydralyte_au", nameKR: "하이드랄라이트 (ORS)", nameVN: "Hydralyte (ORS)", nameUS: "Hydralyte (ORS)", nameAU: "Hydralyte", nameLocal: "Hydralyte", pronKR: "하이드랄라이트", pronEN: "hi-dra-lite", ingredient: "Oral Rehydration Salts (Na, K, Cl, Glucose, Citrate)", dosageKR: "발포정 또는 1포, 물에 타서 소량씩", dosageVN: "Viên sủi hoặc 1 gói, pha nước, uống từng chút", dosageUS: "Effervescent tab or 1 sachet in water, sip frequently", dosageAU: "Effervescent tablet or powder sachet dissolved in water, sip frequently. Available in multiple forms (tablet, powder, icy pole, ready-to-drink)", precautionKR: "끓인 후 식힌 물. 24시간 내 사용", precautionVN: "Nước đun sôi để nguội. Dùng trong 24 giờ", precautionUS: "Boiled cooled water. Use within 24hrs", precautionAU: "Use cooled boiled water. Use within 24hrs. AU's leading ORS brand" },

kwells_au: { id: "kwells_au", nameKR: "크웰스", nameVN: "Kwells", nameUS: "Kwells", nameAU: "Kwells", ingredient: "Hyoscine Hydrobromide 300mcg", dosageKR: "1정, 출발 20~30분 전, 혀 밑에 녹여", dosageVN: "1 viên, 20~30 phút trước đi, ngậm dưới lưỡi", dosageUS: "1 tab, 20-30min before travel, under tongue", dosageAU: "1 tablet, 20-30 minutes before travel, suck or chew. Max 3 in 24hrs. S3 Pharmacist Only", precautionKR: "S3 약사 상담 필수. 10세 미만 금지. 녹내장·전립선비대 금기. 운전 금지", precautionVN: "S3 phải hỏi dược sĩ. Cấm dưới 10 tuổi. Glôcôm cấm", precautionUS: "S3 pharmacist only. No under 10. Glaucoma/prostate contraindicated", precautionAU: "S3 Pharmacist Only Medicine. Not for under 10 (use Kwells Kids 150mcg for 4+). Glaucoma/prostate contraindicated. May cause drowsiness" },

stingose_au: { id: "stingose_au", nameKR: "스팅고즈", nameVN: "Stingose", nameUS: "Stingose", nameAU: "Stingose", nameLocal: "Stingose", pronKR: "스팅고즈", pronEN: "sting-oze", ingredient: "Aluminium Sulfate 20%", dosageKR: "물린/쏘인 부위에 스프레이 또는 도포", dosageVN: "Xịt hoặc thoa vào vùng bị đốt/cắn", dosageUS: "Spray or apply to bite/sting area", dosageAU: "Spray or apply to insect bite/sting area immediately. S2", precautionKR: "2세 미만 금지. 깊은 상처 금지. ⚠️ 박스 해파리는 Stingose 불가→즉시 000 호출", precautionVN: "Cấm dưới 2 tuổi. Không dùng cho vết thương sâu. ⚠️ Sứa hộp→gọi 000 ngay", precautionUS: "No under 2. Not for deep wounds. ⚠️ Box jellyfish→call 000 immediately", precautionAU: "Not for under 2. Not for deep wounds. ⚠️ Box jellyfish (nth QLD): Stingose insufficient→call 000 immediately. Essential AU travel item" },

nurofen_gel_au: { id: "nurofen_gel_au", nameKR: "뉴로펜 겔", nameVN: "Nurofen Gel", nameUS: "Nurofen Gel", nameAU: "Nurofen Gel", ingredient: "Ibuprofen 5%", dosageKR: "아픈 부위에 하루 3~4회, 최대 2주", dosageVN: "Thoa vùng đau 3~4 lần/ngày, tối đa 2 tuần", dosageUS: "Apply 3-4 times/day, max 2 weeks", dosageAU: "Apply to affected area 3-4 times daily, max 2 weeks. S2", precautionKR: "상처·발진 부위 금지. 아스피린 알레르기 주의", precautionVN: "Không thoa lên vết thương. Dị ứng aspirin cẩn thận", precautionUS: "Not on wounds/rash. Aspirin allergy caution", precautionAU: "Not on broken skin/rash. Aspirin allergy caution" },

voltaren_au: { id: "voltaren_au", nameKR: "볼타렌 에멀젤", nameVN: "Voltaren Emulgel", nameUS: "Voltaren Emulgel", nameAU: "Voltaren Emulgel", ingredient: "Diclofenac Diethylammonium 1.16%", dosageKR: "하루 3~4회 도포", dosageVN: "Thoa 3~4 lần/ngày", dosageUS: "Apply 3-4 times/day", dosageAU: "Apply 3-4 times daily. S2. ⚠️ AU strong UV—cover treated area from sun", precautionKR: "광과민성→도포 부위 햇빛 주의(호주 자외선 특히 강함!). 임신 30주 이후 금기", precautionVN: "Tránh nắng vùng thoa (UV Úc rất mạnh!). Cấm sau 30 tuần thai", precautionUS: "Photosensitivity—cover from sun. No after 30wks pregnancy", precautionAU: "Photosensitivity—protect treated area from sunlight (AU UV is extremely strong!). Not after 30 weeks pregnancy" },

restavit_au: { id: "restavit_au", nameKR: "레스타빗", nameVN: "Restavit", nameUS: "Restavit", nameAU: "Restavit", nameLocal: "Restavit", pronKR: "레스타빗", pronEN: "res-ta-vit", ingredient: "Doxylamine Succinate 25mg", dosageKR: "1~2정, 취침 20분 전", dosageVN: "1~2 viên, 20 phút trước ngủ", dosageUS: "1-2 tabs, 20min before bed", dosageAU: "1-2 tablets, 20 minutes before bedtime. S3 Pharmacist Only Medicine", precautionKR: "S3 약사 상담 필수. 7일 이상 금지. 녹내장·전립선비대 금기. 음주 금지. 다음 날 졸음 주의", precautionVN: "S3 phải hỏi dược sĩ. Không quá 7 ngày. Glôcôm cấm. Không uống rượu", precautionUS: "S3 pharmacist only. No more than 7 days. Glaucoma/prostate contraindicated. No alcohol", precautionAU: "S3 Pharmacist Only. Do not use for more than a few days at a time. Glaucoma/prostate enlargement contraindicated. Never with alcohol. Next-day drowsiness possible—do not drive" },

coloxyl_senna_au: { id: "coloxyl_senna_au", nameKR: "콜록실+센나", nameVN: "Coloxyl+Senna", nameUS: "Coloxyl+Senna", nameAU: "Coloxyl with Senna", nameLocal: "Coloxyl with Senna", pronKR: "콜록실 위드 센나", pronEN: "co-lox-il with sen-na", ingredient: "Docusate Sodium + Sennosides", dosageKR: "1~2정, 취침 전", dosageVN: "1~2 viên, trước ngủ", dosageUS: "1-2 tabs, at bedtime", dosageAU: "1-2 tablets, at bedtime. Effect in 8-12 hours. S2", precautionKR: "장기 복용 금지(장 의존성). 복통·장폐색 시 금지", precautionVN: "Không dùng lâu dài. Đau bụng/tắc ruột cấm", precautionUS: "No long-term use. Abdominal pain/obstruction prohibited", precautionAU: "Do not use long-term (bowel dependency). Not with abdominal pain or suspected obstruction. S2" },

strepsils_au: { id: "strepsils_au", nameKR: "스트렙실스", nameVN: "Strepsils", nameUS: "Strepsils", nameAU: "Strepsils", ingredient: "Amylmetacresol + Dichlorobenzyl alcohol", dosageKR: "1정, 2~3시간 간격, 하루 최대 8정", dosageVN: "1 viên, cách 2~3 giờ, tối đa 8 viên/ngày", dosageUS: "1 lozenge, every 2-3hrs, max 8/day", dosageAU: "1 lozenge, every 2-3 hours, max 8/day. S2", precautionKR: "6세 미만 금지", precautionVN: "Cấm dưới 6 tuổi", precautionUS: "No under 6", precautionAU: "Not for children under 6" },

panadol_children_au: { id: "panadol_children_au", nameKR: "파나돌 칠드런 (어린이)", nameVN: "Panadol Children (trẻ em)", nameUS: "Panadol Children", nameAU: "Panadol Children", ingredient: "Paracetamol 120mg/5ml (1-5yr) or 250mg/5ml (5-12yr)", dosageKR: "체중 기준(10~15mg/kg), 4~6시간, 하루 최대 5회", dosageVN: "Theo cân nặng, cách 4~6 giờ, tối đa 5 lần/ngày", dosageUS: "Weight-based, every 4-6hrs, max 5/day", dosageAU: "Weight-based (10-15mg/kg), every 4-6 hours, max 5 doses/day. S2. Not for under 1 month without GP", precautionKR: "1세 미만 의사 처방 필요. 하루 5회 초과 금지. 48시간 이상 발열→의사", precautionVN: "Dưới 1 tuổi cần bác sĩ. Không quá 5 lần/ngày. Sốt 48 giờ→bác sĩ", precautionUS: "Under 1: doctor required. Max 5/day. Fever 48hrs→doctor", precautionAU: "Under 1 month: GP prescription required. Max 5 doses/day. Fever persisting 48hrs→see GP" },

betadine_au: { id: "betadine_au", nameKR: "베타딘", nameVN: "Betadine", nameUS: "Betadine", nameAU: "Betadine", ingredient: "Povidone-iodine 10%", dosageKR: "상처 소독, 도포", dosageVN: "Sát trùng vết thương, thoa", dosageUS: "Wound disinfection, apply", dosageAU: "Apply to wound for disinfection. S2", precautionKR: "갑상선질환 주의. 요오드 알레르기 금기", precautionVN: "Bệnh tuyến giáp cẩn thận. Dị ứng iốt cấm", precautionUS: "Thyroid disease caution. Iodine allergy prohibited", precautionAU: "Thyroid disease caution (iodine absorption). Iodine allergy contraindicated" },

burnaid_au: { id: "burnaid_au", nameKR: "번에이드 (화상 전용)", nameVN: "Burnaid", nameUS: "Burnaid", nameAU: "Burnaid", nameLocal: "Burnaid", pronKR: "번에이드", pronEN: "burn-aid", ingredient: "Melaleuca (Tea Tree) oil + Hydrogel base", dosageKR: "화상 부위에 도포 (20분 냉각 후)", dosageVN: "Thoa vùng bỏng (sau khi làm mát 20 phút)", dosageUS: "Apply to burn (after 20min cooling)", dosageAU: "Apply to burn after cooling under running water for 20 minutes. S2. For minor (1st degree) burns only", precautionKR: "2도 이상·넓은 면적·얼굴 화상→즉시 병원. Tea Tree 알레르기 주의", precautionVN: "Bỏng nặng/diện rộng/mặt→bệnh viện ngay. Dị ứng Tea Tree cẩn thận", precautionUS: "Severe/wide/face burns→hospital immediately. Tea tree allergy caution", precautionAU: "2nd degree+ burns, large area, or face→call 000 or go to ED. Tea tree allergy caution. AU burn care essential" },

canesten_au: { id: "canesten_au", nameKR: "카네스텐", nameVN: "Canesten", nameUS: "Canesten", nameAU: "Canesten", ingredient: "Clotrimazole 1%", dosageKR: "하루 2~3회, 4주 이상", dosageVN: "2~3 lần/ngày, trên 4 tuần", dosageUS: "2-3 times/day, 4+ weeks", dosageAU: "2-3 times daily, at least 4 weeks. S2", precautionKR: "증상 후 2주 더 사용. 콘돔 손상 가능", precautionVN: "Dùng thêm 2 tuần. Có thể hỏng bao cao su", precautionUS: "Continue 2 weeks after symptoms clear. May damage condoms", precautionAU: "Continue 2 weeks after symptoms resolve. May damage latex condoms/diaphragms" },

benzac_au: { id: "benzac_au", nameKR: "벤작 AC", nameVN: "Benzac AC", nameUS: "Benzac AC", nameAU: "Benzac AC", ingredient: "Benzoyl Peroxide 2.5% or 5%", dosageKR: "세안 후 하루 1~2회 도포", dosageVN: "Thoa sau rửa mặt, 1~2 lần/ngày", dosageUS: "Apply after cleansing, 1-2 times/day", dosageAU: "Apply after cleansing, 1-2 times daily. S3 Pharmacist Only Medicine", precautionKR: "S3 약사 상담 필수. 옷 탈색 주의. 눈·입술 금지. 소량 테스트 후 사용", precautionVN: "S3 phải hỏi dược sĩ. Tẩy màu quần áo. Tránh mắt/môi", precautionUS: "S3 pharmacist only. Bleaches fabrics. No eyes/lips. Patch test first", precautionAU: "S3 Pharmacist Only. Bleaches fabrics/towels. Avoid eyes/lips/mucous membranes. Start with 2.5% and small area" },
