// === Germany (DE) Drugs ===
ibuprofen_400_de: { id: "ibuprofen_400_de", nameKR: "이부프로펜 400mg", nameVN: "Ibuprofen 400mg", nameUS: "Ibuprofen 400mg", nameDE: "Ibuprofen 400 ratiopharm", ingredient: "Ibuprofen 400mg", dosageKR: "1정, 식후, 하루 최대 3회(1200mg)", dosageVN: "1 viên, sau ăn, tối đa 3 lần/ngày", dosageUS: "1 tab, with food, max 3 times/day (1200mg)", dosageDE: "1 Tablette, nach dem Essen, max. 3x täglich (1200mg). Apothekenpflichtig", precautionKR: "공복 금지. 임신 20주 이후 금기. 위궤양·위장출혈 금기", precautionVN: "Không uống lúc đói. Cấm sau 20 tuần thai", precautionUS: "Not on empty stomach. No after 20wks pregnancy", precautionDE: "Nicht auf nüchternen Magen. Kontraindiziert ab 20. SSW. Magen-Darm-Blutung Risiko" },

aspirin_de: { id: "aspirin_de", nameKR: "아스피린", nameVN: "Aspirin", nameUS: "Aspirin", nameDE: "Aspirin 500mg", nameLocal: "Aspirin", ingredient: "Acetylsalicylsäure (ASS) 500mg", dosageKR: "1~2정, 4~6시간 간격", dosageVN: "1~2 viên, cách 4~6 giờ", dosageUS: "1-2 tabs, every 4-6hrs", dosageDE: "1-2 Tabletten, alle 4-6 Stunden. Apothekenpflichtig", precautionKR: "12세 미만 금기(Reye 증후군). 위장 출혈 주의. 항응고제 병용 주의", precautionVN: "Cấm dưới 12 tuổi (Reye). Chảy máu dạ dày cẩn thận", precautionUS: "No under 12 (Reye). GI bleeding risk. Anticoagulant interaction", precautionDE: "Unter 12 Jahren kontraindiziert (Reye-Syndrom). GI-Blutungsrisiko. Antikoagulanzien-Wechselwirkung" },

paracetamol_de: { id: "paracetamol_de", nameKR: "파라세타몰 (벤유론)", nameVN: "Paracetamol (ben-u-ron)", nameUS: "Paracetamol (ben-u-ron)", nameDE: "Paracetamol 500mg ratiopharm / ben-u-ron", nameLocal: "ben-u-ron", pronKR: "벤유론", pronEN: "ben-u-ron", ingredient: "Paracetamol 500mg", dosageKR: "1~2정, 4~6시간 간격, 하루 최대 8정(4g)", dosageVN: "1~2 viên, cách 4~6 giờ, tối đa 8 viên/ngày", dosageUS: "1-2 tabs, every 4-6hrs, max 8/day (4g)", dosageDE: "1-2 Tabletten, alle 4-6 Stunden, max. 8/Tag (4g). Apothekenpflichtig", precautionKR: "간독성, 음주자 주의. 다른 파라세타몰 약 중복 금지", precautionVN: "Nguy cơ gan, người uống rượu cẩn thận. Không dùng chung paracetamol khác", precautionUS: "Liver toxicity, alcohol users caution. No other paracetamol products", precautionDE: "Lebertoxizität, Alkohol-Vorsicht. Keine anderen Paracetamol-Produkte gleichzeitig" },

thomapyrin_de: { id: "thomapyrin_de", nameKR: "토마피린 클라식", nameVN: "Thomapyrin Classic", nameUS: "Thomapyrin Classic", nameDE: "Thomapyrin CLASSIC", nameLocal: "Thomapyrin CLASSIC", pronKR: "토마피린 클라식", pronEN: "to-ma-py-rin clas-sic", ingredient: "ASS 250mg + Paracetamol 200mg + Coffein 50mg", dosageKR: "1~2정, 4~8시간 간격, 하루 최대 6정", dosageVN: "1~2 viên, cách 4~8 giờ, tối đa 6 viên/ngày", dosageUS: "1-2 tabs, every 4-8hrs, max 6/day", dosageDE: "1-2 Tabletten, alle 4-8 Stunden, max. 6 Tabletten/Tag. Ab 12 Jahren", precautionKR: "12세 미만 금기(ASS→Reye). 다른 파라세타몰/ASS 약 병용 금지. 임신 3분기 금기. 장기복용→약물남용성 두통", precautionVN: "Cấm dưới 12 tuổi. Không dùng chung paracetamol/ASS khác. Cấm 3 tháng cuối thai kỳ", precautionUS: "No under 12 (Reye). No other paracetamol/ASS. No in 3rd trimester. Long-term→MOH risk", precautionDE: "Unter 12 Jahren kontraindiziert (Reye). Keine anderen Paracetamol/ASS-Produkte. 3. Trimenon kontraindiziert. Langfristig→Medikamenten-Übergebrauchskopfschmerz" },

grippostad_de: { id: "grippostad_de", nameKR: "그리포스타트 C", nameVN: "Grippostad C", nameUS: "Grippostad C", nameDE: "Grippostad C", nameLocal: "Grippostad C", pronKR: "그리포스타트 체", pronEN: "grip-po-stat tsay", ingredient: "Paracetamol 200mg + Vitamin C 150mg + Coffein 25mg + Chlorphenamin 2.5mg (per capsule)", dosageKR: "2캡슐, 하루 3회, 12세 이상", dosageVN: "2 viên, 3 lần/ngày, từ 12 tuổi", dosageUS: "2 capsules, 3 times/day, 12+ years", dosageDE: "2 Kapseln, 3x täglich. Ab 12 Jahren. Apothekenpflichtig", precautionKR: "졸음→운전 금지. 다른 파라세타몰 약 병용 금지. 임산부·수유부 금기. 3일 이상 금지", precautionVN: "Buồn ngủ→không lái xe. Không dùng chung paracetamol khác. Thai phụ cấm", precautionUS: "Drowsy→no driving. No other paracetamol. Pregnancy/breastfeeding contraindicated. Max 3 days", precautionDE: "Schläfrigkeit→nicht fahren. Keine anderen Paracetamol-Produkte. Schwangerschaft/Stillzeit kontraindiziert. Max. 3 Tage" },

aspirin_complex_de: { id: "aspirin_complex_de", nameKR: "아스피린 콤플렉스", nameVN: "Aspirin Complex", nameUS: "Aspirin Complex", nameDE: "Aspirin Complex", nameLocal: "Aspirin Complex", pronKR: "아스피린 콤플렉스", pronEN: "as-pi-rin com-plex", ingredient: "ASS 500mg + Pseudoephedrin HCl 30mg", dosageKR: "1포, 물에 녹여, 하루 3~4회", dosageVN: "1 gói pha nước, 3~4 lần/ngày", dosageUS: "1 sachet dissolved, 3-4 times/day", dosageDE: "1 Beutel in Wasser lösen, 3-4x täglich. Ab 16 Jahren", precautionKR: "16세 미만 금기. 고혈압·심장·갑상선 금기. MAO 억제제 금기. 위장 출혈 위험", precautionVN: "Cấm dưới 16 tuổi. Cao huyết áp/tim/giáp cấm", precautionUS: "No under 16. Hypertension/heart/thyroid contraindicated. No MAOIs", precautionDE: "Unter 16 Jahren kontraindiziert. Hypertonie/Herz/Schilddrüse kontraindiziert. Keine MAO-Hemmer" },

wick_daymed_de: { id: "wick_daymed_de", nameKR: "빅 데이메드", nameVN: "WICK DayMed", nameUS: "WICK DayMed", nameDE: "WICK DayMed", nameLocal: "WICK DayMed", pronKR: "빅 데이메드", pronEN: "vik day-med", ingredient: "Paracetamol 500mg + Phenylephrin 10mg + DXM 10mg", dosageKR: "1캡슐, 하루 3~4회", dosageVN: "1 viên, 3~4 lần/ngày", dosageUS: "1 capsule, 3-4 times/day", dosageDE: "1 Kapsel, 3-4x täglich. Apothekenpflichtig", precautionKR: "다른 파라세타몰 약 병용 금지. MAO 억제제 금기", precautionVN: "Không dùng chung paracetamol khác. MAOI cấm", precautionUS: "No other paracetamol. No MAOIs", precautionDE: "Keine anderen Paracetamol-Produkte. Keine MAO-Hemmer" },

sinupret_de: { id: "sinupret_de", nameKR: "시누프렛 포르테", nameVN: "Sinupret forte", nameUS: "Sinupret forte", nameDE: "Sinupret forte", nameLocal: "Sinupret forte", pronKR: "지누프렛 포르테", pronEN: "zi-nu-pret for-te", ingredient: "Gentian+Primrose+Verbena+Elderflower+Sorrel (Phytopharmaka)", dosageKR: "1정, 하루 3회, 식후", dosageVN: "1 viên, 3 lần/ngày, sau ăn", dosageUS: "1 tab, 3 times/day, after meals", dosageDE: "1 Tablette, 3x täglich, nach dem Essen. Pflanzliches Arzneimittel", precautionKR: "부비동염·코막힘 식물성 의약품. 임산부 의사 상담", precautionVN: "Thuốc thảo dược viêm xoang. Thai phụ hỏi bác sĩ", precautionUS: "Herbal sinusitis medicine. Pregnancy: consult doctor", precautionDE: "Pflanzliches Sinusitis-Mittel. Schwangerschaft: Arzt konsultieren" },

mucosolvan_de: { id: "mucosolvan_de", nameKR: "무코솔반", nameVN: "Mucosolvan", nameUS: "Mucosolvan", nameDE: "Mucosolvan", nameLocal: "Mucosolvan", pronKR: "무코솔반", pronEN: "mu-ko-sol-van", ingredient: "Ambroxol HCl 30mg", dosageKR: "1정, 하루 2~3회", dosageVN: "1 viên, 2~3 lần/ngày", dosageUS: "1 tab, 2-3 times/day", dosageDE: "1 Tablette, 2-3x täglich. Ausreichend trinken", precautionKR: "충분한 수분 섭취. 소화성 궤양 주의", precautionVN: "Uống nhiều nước. Loét dạ dày cẩn thận", precautionUS: "Drink plenty of water. Peptic ulcer caution", precautionDE: "Ausreichend Flüssigkeit trinken. Magengeschwür Vorsicht" },

acc_600_de: { id: "acc_600_de", nameKR: "ACC 아쿠트 600", nameVN: "ACC Akut 600", nameUS: "ACC Akut 600", nameDE: "ACC akut 600 Brausetabletten", nameLocal: "ACC akut 600", pronKR: "아체체 아쿠트", pronEN: "ah-tse-tse a-koot", ingredient: "Acetylcystein 600mg", dosageKR: "1포(발포정), 물에 녹여, 하루 1회", dosageVN: "1 viên sủi pha nước, 1 lần/ngày", dosageUS: "1 effervescent tab in water, once daily", dosageDE: "1 Brausetablette in Wasser lösen, 1x täglich", precautionKR: "소화성 궤양 주의. 천식 환자 기관지 경련 가능", precautionVN: "Loét dạ dày cẩn thận. Hen suyễn: co thắt phế quản có thể xảy ra", precautionUS: "Peptic ulcer caution. Asthma: bronchospasm possible", precautionDE: "Magengeschwür Vorsicht. Asthma: Bronchospasmus möglich" },

gelomyrtol_de: { id: "gelomyrtol_de", nameKR: "겔로미르톨 포르테", nameVN: "Gelomyrtol forte", nameUS: "Gelomyrtol forte", nameDE: "GeloMyrtol forte", nameLocal: "GeloMyrtol forte", pronKR: "겔로뮈르톨 포르테", pronEN: "ge-lo-myr-tol for-te", ingredient: "Myrtol standardized extract (Eucalyptus+Orange+Myrtle+Lemon oils)", dosageKR: "1캡슐, 식전 30분, 하루 3~4회", dosageVN: "1 viên, 30 phút trước ăn, 3~4 lần/ngày", dosageUS: "1 capsule, 30min before meals, 3-4 times/day", dosageDE: "1 Kapsel, 30 Min. vor dem Essen, 3-4x täglich. Pflanzliches Arzneimittel", precautionKR: "반드시 식전 복용! 5세 이상 소아용(GeloMyrtol 300) 별도", precautionVN: "Phải uống trước ăn! Trẻ 5+ dùng GeloMyrtol 300", precautionUS: "Must take before meals! Children 5+: use GeloMyrtol 300", precautionDE: "Unbedingt vor dem Essen einnehmen! Kinder ab 5: GeloMyrtol 300 verwenden" },

doloDobendan_de: { id: "doloDobendan_de", nameKR: "돌로도벤단", nameVN: "Dolo-Dobendan", nameUS: "Dolo-Dobendan", nameDE: "Dolo-Dobendan", nameLocal: "Dolo-Dobendan", pronKR: "돌로도벤단", pronEN: "do-lo-do-ben-dan", ingredient: "Benzocaine 1.5mg + Cetylpyridiniumchlorid 0.3mg", dosageKR: "1정, 2~3시간 간격, 하루 최대 8정", dosageVN: "1 viên, cách 2~3 giờ, tối đa 8 viên/ngày", dosageUS: "1 lozenge, every 2-3hrs, max 8/day", dosageDE: "1 Lutschtablette, alle 2-3 Stunden, max. 8/Tag", precautionKR: "Benzocaine→메트헤모글로빈혈증 위험(드묾). 2세 미만 금지", precautionVN: "Benzocaine→nguy cơ methemoglobin (hiếm). Cấm dưới 2 tuổi", precautionUS: "Benzocaine→methemoglobinemia risk (rare). No under 2", precautionDE: "Benzocain→Methämoglobinämie-Risiko (selten). Unter 2 Jahren kontraindiziert" },

neoAngin_de: { id: "neoAngin_de", nameKR: "네오앙긴", nameVN: "Neo-Angin", nameUS: "Neo-Angin", nameDE: "Neo-Angin", nameLocal: "Neo-Angin", pronKR: "네오앙긴", pronEN: "ne-o-an-gin", ingredient: "Amylmetacresol + Dichlorobenzylalkohol + Menthol", dosageKR: "1정, 2~3시간 간격", dosageVN: "1 viên, cách 2~3 giờ", dosageUS: "1 lozenge, every 2-3hrs", dosageDE: "1 Lutschtablette, alle 2-3 Stunden", precautionKR: "6세 미만 금지", precautionVN: "Cấm dưới 6 tuổi", precautionUS: "No under 6", precautionDE: "Unter 6 Jahren kontraindiziert" },

xylometazoline_de: { id: "xylometazoline_de", nameKR: "코 스프레이 (자일로메타졸린)", nameVN: "Nasenspray Xylometazoline", nameUS: "Nasal Spray Xylometazoline", nameDE: "Nasenspray ratiopharm Erwachsene", ingredient: "Xylometazolin HCl 0.1%", dosageKR: "1~2회 분사, 하루 2~3회", dosageVN: "1~2 lần xịt, 2~3 lần/ngày", dosageUS: "1-2 sprays, 2-3 times/day", dosageDE: "1-2 Sprühstöße je Nasenloch, 2-3x täglich. Max. 7 Tage", precautionKR: "7일 초과 금지(반동성 코막힘). 6세 미만 소아용 0.05% 사용", precautionVN: "Không dùng quá 7 ngày. Trẻ dưới 6 tuổi dùng 0.05%", precautionUS: "No more than 7 days. Under 6: use 0.05% children's", precautionDE: "Nicht länger als 7 Tage (Rhinitis medicamentosa). Unter 6 Jahren: 0,05% Kinderversion" },

cetirizin_de: { id: "cetirizin_de", nameKR: "세티리진", nameVN: "Cetirizin", nameUS: "Cetirizine", nameDE: "Cetirizin ratiopharm 10mg", ingredient: "Cetirizin HCl 10mg", dosageKR: "1정, 하루 1회(취침 전)", dosageVN: "1 viên, 1 lần/ngày (trước ngủ)", dosageUS: "1 tab, once daily (bedtime)", dosageDE: "1 Tablette, 1x täglich (abends). Apothekenpflichtig", precautionKR: "졸음 가능. 신장질환 시 용량 조절", precautionVN: "Có thể buồn ngủ. Bệnh thận điều chỉnh liều", precautionUS: "May cause drowsiness. Kidney disease: dose adjustment", precautionDE: "Kann Schläfrigkeit verursachen. Nierenerkrankung: Dosisanpassung" },

loratadin_de: { id: "loratadin_de", nameKR: "로라타딘", nameVN: "Loratadin", nameUS: "Loratadine", nameDE: "Loratadin ratiopharm 10mg", ingredient: "Loratadin 10mg", dosageKR: "1정, 하루 1회", dosageVN: "1 viên, 1 lần/ngày", dosageUS: "1 tab, once daily", dosageDE: "1 Tablette, 1x täglich. Apothekenpflichtig", precautionKR: "졸음 매우 적음. 간질환 시 격일 복용", precautionVN: "Ít gây buồn ngủ. Bệnh gan uống cách ngày", precautionUS: "Very low drowsiness. Liver disease: every other day", precautionDE: "Sehr geringe Schläfrigkeit. Lebererkrankung: jeden 2. Tag" },

iberogast_de: { id: "iberogast_de", nameKR: "이베로가스트", nameVN: "Iberogast", nameUS: "Iberogast", nameDE: "Iberogast", nameLocal: "Iberogast", pronKR: "이베로가스트", pronEN: "ee-be-ro-gast", ingredient: "9 Pflanzenextrakte (Iberis amara + 8 weitere)", dosageKR: "20방울, 식전/식간, 하루 3회", dosageVN: "20 giọt, trước/giữa bữa ăn, 3 lần/ngày", dosageUS: "20 drops, before/between meals, 3 times/day", dosageDE: "20 Tropfen, vor/zwischen den Mahlzeiten, 3x täglich", precautionKR: "⚠️ 간독성 위험! Schöllkraut(애기똥풀) 함유→BfArM 경고(2018). 간질환자·임산부 금기. 알코올 31% 함유", precautionVN: "⚠️ Nguy cơ gan! Chứa Schöllkraut→cảnh báo BfArM. Bệnh gan/thai phụ cấm. Cồn 31%", precautionUS: "⚠️ Liver toxicity risk! Contains Chelidonium→BfArM warning(2018). Liver disease/pregnancy contraindicated. 31% alcohol", precautionDE: "⚠️ Lebertoxizitätsrisiko! Enthält Schöllkraut→BfArM-Warnung (2018). Lebererkrankung/Schwangerschaft kontraindiziert. 31 Vol.-% Alkohol" },

maaloxan_de: { id: "maaloxan_de", nameKR: "말록산", nameVN: "Maaloxan", nameUS: "Maaloxan", nameDE: "Maaloxan 25mVal", nameLocal: "Maaloxan", pronKR: "말록산", pronEN: "ma-lox-an", ingredient: "Aluminium hydroxide + Magnesium hydroxide", dosageKR: "1~2정 씹어먹기, 식후 1시간", dosageVN: "1~2 viên nhai, 1 giờ sau ăn", dosageUS: "1-2 chewable tabs, 1hr after meals", dosageDE: "1-2 Kautabletten, 1 Stunde nach dem Essen", precautionKR: "신장질환 금기(Al·Mg 축적). 항생제와 2시간 간격. 14일 이상 시 의사", precautionVN: "Bệnh thận cấm. Cách kháng sinh 2 giờ", precautionUS: "Kidney disease contraindicated. Space antibiotics 2hrs. Over 14 days→doctor", precautionDE: "Niereninsuffizienz kontraindiziert. 2 Stunden Abstand zu Antibiotika. Über 14 Tage→Arzt" },

omeprazol_de: { id: "omeprazol_de", nameKR: "오메프라졸", nameVN: "Omeprazol", nameUS: "Omeprazole", nameDE: "Omeprazol ratiopharm 20mg", ingredient: "Omeprazol 20mg", dosageKR: "1정, 아침 식전, 14일 코스", dosageVN: "1 viên, trước bữa sáng, 14 ngày", dosageUS: "1 tab, before breakfast, 14-day course", dosageDE: "1 Tablette, vor dem Frühstück, 14 Tage. Apothekenpflichtig", precautionKR: "14일 초과 자가 복용 금지. 클로피도그렐 병용 금기", precautionVN: "Không quá 14 ngày tự dùng. Clopidogrel cấm dùng chung", precautionUS: "No more than 14 days self-treatment. Clopidogrel contraindicated", precautionDE: "Max. 14 Tage Selbstmedikation. Clopidogrel kontraindiziert" },

imodium_de: { id: "imodium_de", nameKR: "이모디움 아쿠트", nameVN: "Imodium akut", nameUS: "Imodium akut", nameDE: "Imodium akut", ingredient: "Loperamid HCl 2mg", dosageKR: "초회 2정, 이후 설사마다 1정, 하루 최대 8정", dosageVN: "Đầu tiên 2 viên, sau mỗi lần 1 viên, tối đa 8/ngày", dosageUS: "First 2 tabs, then 1 per stool, max 8/day", dosageDE: "Anfangs 2 Tabletten, dann 1 nach jedem Stuhl, max. 8/Tag", precautionKR: "12세 미만 금지. 혈변·발열 시 금지. 48시간 이내 개선 없으면 의사", precautionVN: "Cấm dưới 12 tuổi. Máu/sốt cấm. 48 giờ→bác sĩ", precautionUS: "No under 12. No bloody stool/fever. 48hrs→doctor", precautionDE: "Unter 12 Jahren kontraindiziert. Kein Blut im Stuhl/Fieber. 48 Stunden→Arzt" },

perenterol_de: { id: "perenterol_de", nameKR: "페렌테롤", nameVN: "Perenterol", nameUS: "Perenterol", nameDE: "Perenterol forte 250mg", nameLocal: "Perenterol", pronKR: "페렌테롤", pronEN: "pe-ren-te-rol", ingredient: "Saccharomyces cerevisiae HANSEN CBS 5926 (medizinische Hefe)", dosageKR: "1~2캡슐, 하루 1~2회", dosageVN: "1~2 viên, 1~2 lần/ngày", dosageUS: "1-2 capsules, 1-2 times/day", dosageDE: "1-2 Kapseln, 1-2x täglich. Apothekenpflichtig", precautionKR: "면역저하 환자 진균 혈증 위험→의사 상담. 중앙정맥 카테터 환자 금기", precautionVN: "Người suy giảm miễn dịch→hỏi bác sĩ. Catheter tĩnh mạch trung tâm cấm", precautionUS: "Immunocompromised: fungemia risk→consult doctor. Central venous catheter contraindicated", precautionDE: "Immunsupprimierte: Fungämie-Risiko→Arzt konsultieren. Zentralvenöser Katheter kontraindiziert" },

elotrans_de: { id: "elotrans_de", nameKR: "엘로트란스 (ORS)", nameVN: "Elotrans (ORS)", nameUS: "Elotrans (ORS)", nameDE: "Elotrans Pulver", nameLocal: "Elotrans", pronKR: "엘로트란스", pronEN: "e-lo-trans", ingredient: "Elektrolyte (Na, K, Cl, Citrat, Glucose)", dosageKR: "1포, 물에 타서 소량씩", dosageVN: "1 gói pha nước, uống từng chút", dosageUS: "1 sachet in water, sip frequently", dosageDE: "1 Beutel in Wasser auflösen, schluckweise trinken. Auch beliebt als Kater-Mittel!", precautionKR: "끓인 후 식힌 물. 24시간 내 사용. 독일인 숙취 해소 인기 제품!", precautionVN: "Nước đun sôi để nguội. Dùng trong 24 giờ. Người Đức hay dùng trị hangover!", precautionUS: "Boiled cooled water. Use within 24hrs. Popular hangover remedy in Germany!", precautionDE: "Abgekochtes, abgekühltes Wasser. Innerhalb 24 Stunden verbrauchen. Beliebtes Kater-Mittel!" },

vomex_de: { id: "vomex_de", nameKR: "보멕스 A", nameVN: "Vomex A", nameUS: "Vomex A", nameDE: "Vomex A", nameLocal: "Vomex A", pronKR: "보멕스 아", pronEN: "vo-meks ah", ingredient: "Dimenhydrinat 50mg", dosageKR: "1정, 출발 30분 전, 하루 최대 8정", dosageVN: "1 viên, 30 phút trước đi, tối đa 8 viên/ngày", dosageUS: "1 tab, 30min before travel, max 8/day", dosageDE: "1 Tablette, 30 Min. vor der Reise, max. 8/Tag (400mg). Apothekenpflichtig", precautionKR: "졸음→운전 금지. 녹내장·전립선비대 금기. 음주 금지", precautionVN: "Buồn ngủ→không lái xe. Glôcôm/tiền liệt tuyến cấm. Không uống rượu", precautionUS: "Drowsy→no driving. Glaucoma/prostate contraindicated. No alcohol", precautionDE: "Schläfrigkeit→nicht fahren. Glaukom/Prostatahyperplasie kontraindiziert. Kein Alkohol" },

voltaren_de: { id: "voltaren_de", nameKR: "볼타렌 슈메르츠겔", nameVN: "Voltaren Schmerzgel", nameUS: "Voltaren Schmerzgel", nameDE: "Voltaren Schmerzgel", nameLocal: "Voltaren Schmerzgel", pronKR: "볼타렌 슈메르츠겔", pronEN: "vol-ta-ren shmertz-gel", ingredient: "Diclofenac Diethylammonium (1% Diclofenac-Na)", dosageKR: "하루 3~4회 도포, 최대 2주", dosageVN: "Thoa 3~4 lần/ngày, tối đa 2 tuần", dosageUS: "Apply 3-4 times/day, max 2 weeks", dosageDE: "3-4x täglich auftragen, max. 2 Wochen. Apothekenpflichtig", precautionKR: "광과민성→도포 부위 햇빛 주의. 임신 30주 이후 금기", precautionVN: "Tránh nắng vùng thoa. Cấm sau 30 tuần thai", precautionUS: "Photosensitivity. No after 30wks pregnancy", precautionDE: "Photosensitivität→behandelte Stelle vor Sonne schützen. Ab 30. SSW kontraindiziert" },

fenistil_de: { id: "fenistil_de", nameKR: "페니스틸 겔", nameVN: "Fenistil Gel", nameUS: "Fenistil Gel", nameDE: "Fenistil Gel", nameLocal: "Fenistil", pronKR: "페니스틸", pronEN: "fe-nis-til", ingredient: "Dimetindenmaleat 0.1%", dosageKR: "환부에 하루 2~4회 도포", dosageVN: "Thoa 2~4 lần/ngày", dosageUS: "Apply 2-4 times/day", dosageDE: "2-4x täglich auftragen. Apothekenpflichtig", precautionKR: "2세 미만 의사 상담. 눈·점막 금지", precautionVN: "Dưới 2 tuổi hỏi bác sĩ. Tránh mắt/niêm mạc", precautionUS: "Under 2: consult doctor. No eyes/mucous", precautionDE: "Unter 2 Jahren: Arzt konsultieren. Nicht an Augen/Schleimhäuten" },

bepanthen_eye_de: { id: "bepanthen_eye_de", nameKR: "베판텐 안약", nameVN: "Bepanthen Augentropfen", nameUS: "Bepanthen Eye Drops", nameDE: "Bepanthen Augentropfen", nameLocal: "Bepanthen Augentropfen", pronKR: "베판텐 아우겐트롭펜", pronEN: "be-pan-ten ow-gen-trop-fen", ingredient: "Dexpanthenol 50mg/ml (5%)", dosageKR: "1방울, 하루 수회", dosageVN: "1 giọt, nhiều lần/ngày", dosageUS: "1 drop, several times/day", dosageDE: "1 Tropfen, mehrmals täglich. Apothekenpflichtig", precautionKR: "렌즈 빼고 사용, 15분 후 재착용", precautionVN: "Tháo kính áp tròng, đeo lại sau 15 phút", precautionUS: "Remove contacts, reinsert after 15min", precautionDE: "Kontaktlinsen entfernen, nach 15 Min. wieder einsetzen" },

kamistad_de: { id: "kamistad_de", nameKR: "카미스타트 겔", nameVN: "Kamistad Gel", nameUS: "Kamistad Gel", nameDE: "Kamistad Gel", nameLocal: "Kamistad", pronKR: "카미스타트", pronEN: "ka-mi-stat", ingredient: "Lidocain HCl + Kamillenblüten-Extrakt", dosageKR: "환부에 소량 도포, 하루 3회", dosageVN: "Thoa ít lên vết loét, 3 lần/ngày", dosageUS: "Apply small amount, 3 times/day", dosageDE: "Erbsengroße Menge auftragen, 3x täglich", precautionKR: "국화과 알레르기 주의(캐모마일)", precautionVN: "Dị ứng họ cúc cẩn thận (hoa cúc)", precautionUS: "Asteraceae allergy caution (chamomile)", precautionDE: "Korbblütler-Allergie beachten (Kamille)" },

dulcolax_de: { id: "dulcolax_de", nameKR: "둘코락스", nameVN: "Dulcolax", nameUS: "Dulcolax", nameDE: "Dulcolax Dragées", ingredient: "Bisacodyl 5mg", dosageKR: "1~2정, 취침 전", dosageVN: "1~2 viên, trước ngủ", dosageUS: "1-2 tabs, at bedtime", dosageDE: "1-2 Dragées, abends vor dem Schlafengehen", precautionKR: "장기 복용 금지. 우유·제산제와 1시간 간격. 6세 미만 금지", precautionVN: "Không dùng lâu dài. Cách sữa/antacid 1 giờ. Dưới 6 tuổi cấm", precautionUS: "No long-term use. Space milk/antacids 1hr. No under 6", precautionDE: "Nicht dauerhaft einnehmen. 1 Stunde Abstand zu Milch/Antazida. Unter 6 Jahren kontraindiziert" },

movicol_de: { id: "movicol_de", nameKR: "모비콜", nameVN: "Movicol", nameUS: "Movicol", nameDE: "Movicol", nameLocal: "Movicol", pronKR: "모비콜", pronEN: "mo-vi-col", ingredient: "Macrogol 3350 13.125g + Elektrolyte", dosageKR: "1포, 물 125ml에, 하루 1~3회", dosageVN: "1 gói pha 125ml nước, 1~3 lần/ngày", dosageUS: "1 sachet in 125ml water, 1-3 times/day", dosageDE: "1 Beutel in 125ml Wasser, 1-3x täglich. Keine Gewöhnung", precautionKR: "충분한 수분. 장폐색 금기. 의존성 없음", precautionVN: "Uống đủ nước. Tắc ruột cấm. Không gây lệ thuộc", precautionUS: "Adequate fluids. Bowel obstruction contraindicated. No dependency", precautionDE: "Ausreichend trinken. Darmverschluss kontraindiziert. Keine Gewöhnung" },

bepanthen_de: { id: "bepanthen_de", nameKR: "베판텐 상처연고", nameVN: "Bepanthen Wundsalbe", nameUS: "Bepanthen Wound Ointment", nameDE: "Bepanthen Wund- und Heilsalbe", nameLocal: "Bepanthen", pronKR: "베판텐", pronEN: "be-pan-ten", ingredient: "Dexpanthenol 5% (50mg/g)", dosageKR: "환부에 하루 수회 도포", dosageVN: "Thoa nhiều lần/ngày", dosageUS: "Apply several times/day", dosageDE: "Mehrmals täglich dünn auftragen. Deutschlands beliebteste Wundsalbe", precautionKR: "감염 상처는 먼저 소독 필요", precautionVN: "Vết thương nhiễm trùng cần sát trùng trước", precautionUS: "Infected wounds need disinfection first", precautionDE: "Infizierte Wunden zuerst desinfizieren" },

betaisodona_de: { id: "betaisodona_de", nameKR: "베타이소도나", nameVN: "Betaisodona", nameUS: "Betaisodona", nameDE: "Betaisodona Salbe/Lösung", nameLocal: "Betaisodona", pronKR: "베타이소도나", pronEN: "be-ta-ee-so-do-na", ingredient: "Povidon-Iod 10%", dosageKR: "상처 소독, 도포", dosageVN: "Sát trùng vết thương, thoa", dosageUS: "Wound disinfection, apply", dosageDE: "Zur Wunddesinfektion auftragen. Apothekenpflichtig", precautionKR: "갑상선질환 주의(요오드). 요오드 알레르기 금기", precautionVN: "Bệnh tuyến giáp cẩn thận. Dị ứng iốt cấm", precautionUS: "Thyroid disease caution. Iodine allergy prohibited", precautionDE: "Schilddrüsenerkrankung Vorsicht (Jodaufnahme). Jodallergie kontraindiziert" },

hoggar_de: { id: "hoggar_de", nameKR: "호가 나이트", nameVN: "Hoggar Night", nameUS: "Hoggar Night", nameDE: "Hoggar Night", nameLocal: "Hoggar Night", pronKR: "호가 나이트", pronEN: "ho-gar night", ingredient: "Doxylaminsuccinat 25mg", dosageKR: "반~1정, 취침 30분 전", dosageVN: "½~1 viên, 30 phút trước ngủ", dosageUS: "½-1 tab, 30min before bed", dosageDE: "½-1 Tablette, 30 Min. vor dem Schlafengehen. Max. 7 Tage. Apothekenpflichtig", precautionKR: "7일 이상 금지. 녹내장·전립선비대 금기. 음주 금지. 65세 이상 낙상·인지저하 위험", precautionVN: "Không quá 7 ngày. Glôcôm/tiền liệt tuyến cấm. Không rượu. 65+ ngã/suy giảm nhận thức", precautionUS: "No more than 7 days. Glaucoma/prostate contraindicated. No alcohol. 65+: fall/cognitive risk", precautionDE: "Max. 7 Tage. Glaukom/Prostatahyperplasie kontraindiziert. Kein Alkohol. 65+: Sturzgefahr/kognitive Beeinträchtigung" },

canesten_de: { id: "canesten_de", nameKR: "카네스텐", nameVN: "Canesten", nameUS: "Canesten", nameDE: "Canesten Creme", ingredient: "Clotrimazol 1%", dosageKR: "하루 2~3회, 4주 이상", dosageVN: "2~3 lần/ngày, trên 4 tuần", dosageUS: "2-3 times/day, 4+ weeks", dosageDE: "2-3x täglich, mindestens 4 Wochen. Bayer-Produkt (deutsches Unternehmen!)", precautionKR: "증상 후 2주 더 사용(재발 방지). Bayer 본사 제품!", precautionVN: "Dùng thêm 2 tuần sau khi hết. Sản phẩm Bayer (công ty Đức!)", precautionUS: "Continue 2 weeks after symptoms clear. Bayer product (German company!)", precautionDE: "2 Wochen nach Symptomfreiheit weiter anwenden. Bayer-Produkt!" },

lamisil_de: { id: "lamisil_de", nameKR: "라미실", nameVN: "Lamisil", nameUS: "Lamisil", nameDE: "Lamisil Creme", ingredient: "Terbinafin HCl 1%", dosageKR: "하루 1~2회, 1~2주", dosageVN: "1~2 lần/ngày, 1~2 tuần", dosageUS: "1-2 times/day, 1-2 weeks", dosageDE: "1-2x täglich, 1-2 Wochen", precautionKR: "완치 후 1주 추가 도포", precautionVN: "Dùng thêm 1 tuần sau khi khỏi", precautionUS: "Continue 1 week after cure", precautionDE: "1 Woche nach Abheilung weiter anwenden" },

benzaknen_de: { id: "benzaknen_de", nameKR: "벤작넨", nameVN: "Benzaknen", nameUS: "Benzaknen", nameDE: "Benzaknen 5%", nameLocal: "Benzaknen", pronKR: "벤작넨", pronEN: "ben-zak-nen", ingredient: "Benzoylperoxid 5%", dosageKR: "세안 후 하루 1~2회 도포", dosageVN: "Thoa sau rửa mặt, 1~2 lần/ngày", dosageUS: "Apply after cleansing, 1-2 times/day", dosageDE: "Nach Reinigung 1-2x täglich auftragen. Apothekenpflichtig", precautionKR: "옷 탈색 주의. 눈·점막 금지. 소량 테스트 후 시작", precautionVN: "Cẩn thận tẩy màu quần áo. Tránh mắt/niêm mạc", precautionUS: "Bleaches fabrics. No eyes/mucous. Patch test first", precautionDE: "Bleicht Textilien. Nicht an Augen/Schleimhäuten. Erst mit kleiner Fläche testen" },

nurofen_junior_de: { id: "nurofen_junior_de", nameKR: "뉴로펜 주니어 시럽 (어린이)", nameVN: "Nurofen Junior Fiebersaft (trẻ em)", nameUS: "Nurofen Junior Syrup (children)", nameDE: "Nurofen Junior Fiebersaft", ingredient: "Ibuprofen 20mg/ml (2-8yr) or 40mg/ml (6-12yr)", dosageKR: "체중 기준(3개월+, 5kg+), 6~8시간 간격", dosageVN: "Theo cân nặng (3 tháng+), cách 6~8 giờ", dosageUS: "Weight-based (3mo+, 5kg+), every 6-8hrs", dosageDE: "Gewichtsbasiert (ab 3 Monaten, min. 5kg), alle 6-8 Stunden. Apothekenpflichtig", precautionKR: "6개월 미만 금기. 어린이용 제형만 사용", precautionVN: "Cấm dưới 6 tháng. Chỉ dùng dạng trẻ em", precautionUS: "No under 6 months. Children's formulation only", precautionDE: "Unter 6 Monaten kontraindiziert. Nur Kinder-Darreichungsform verwenden" },

ben_u_ron_de: { id: "ben_u_ron_de", nameKR: "벤유론 시럽 (어린이)", nameVN: "ben-u-ron Saft (trẻ em)", nameUS: "ben-u-ron Syrup (children)", nameDE: "ben-u-ron Saft", nameLocal: "ben-u-ron Saft", pronKR: "벤유론 잡트", pronEN: "ben-u-ron zaft", ingredient: "Paracetamol 200mg/5ml", dosageKR: "체중/연령 기준, 4~6시간 간격", dosageVN: "Theo cân nặng/tuổi, cách 4~6 giờ", dosageUS: "Weight/age based, every 4-6hrs", dosageDE: "Gewichts-/altersbasiert, alle 4-6 Stunden. Deutsches Kinder-Fiebermittel", precautionKR: "다른 파라세타몰 약 중복 금지", precautionVN: "Không dùng chung paracetamol khác", precautionUS: "No other paracetamol products", precautionDE: "Keine anderen Paracetamol-Produkte gleichzeitig" },
